package cn.lnexin.dingtalk.entity;

import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

@Component
@Repository
public class UserMapper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dd_eas_usermapper.id
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dd_eas_usermapper.userid
     *
     * @mbggenerated
     */
    private String USERID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dd_eas_usermapper.usernumber
     *
     * @mbggenerated
     */
    private String USERNUMBER;

    public Integer getID() {
        return ID;
    }

    public void setID(Integer ID) {
        this.ID = ID;
    }

    public String getUSERID() {
        return USERID;
    }

    public void setUSERID(String USERID) {
        this.USERID = USERID;
    }

    public String getUSERNUMBER() {
        return USERNUMBER;
    }

    public void setUSERNUMBER(String USERNUMBER) {
        this.USERNUMBER = USERNUMBER;
    }
}