package cn.lnexin.dingtalk.dao;

import cn.lnexin.dingtalk.entity.UserMapper;
import org.springframework.stereotype.Repository;

@Repository
public interface UserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dd_eas_usermapper
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dd_eas_usermapper
     *
     * @mbggenerated
     */
    int insert(UserMapper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dd_eas_usermapper
     *
     * @mbggenerated
     */
    int insertSelective(UserMapper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dd_eas_usermapper
     *
     * @mbggenerated
     */
    UserMapper selectByPrimaryKey(Integer id);
    UserMapper selectByUserId(UserMapper record);
}